apiVersion: v1
kind: Service
metadata:
  name: app-k8s
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: app-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k8s
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: app-k8s
  template:
    metadata:
      labels:
        app: app-k8s
    spec:
      containers:
        - name: app-k8s
          image: CONTAINER_IMAGE
          resources:
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 3000
          env:
            - name: RDS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: rds
                  key: host
            - name: RDS_PORT
              value: "3306"
            - name: RDS_USERNAME
              value: demoappuser
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds
                  key: password



